import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { classNames } from "@/utils/appearence";
import Navbar from "./components/Navbar";

const inter = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames("bg-color-primary", inter.className)}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
