import Image from "next/image";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import heroImage from "@/public/images/code-bg.jpg";
import { classNames } from "@/utils/appearence";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";

import { robotoMono } from "@/app/fonts/fonts";
import Footer from "./components/Footet";

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames("bg-dark-gray relative", robotoMono.className)}
      >
        <Image
          src={heroImage}
          alt="Motorcycle"
          className="fixed flex-shrink-0 object-cover h-screen"
        />
        <div className="absolute">
          <Navbar />
          {children}
          <Footer />
        </div>
        <Analytics />
      </body>
    </html>
  );
}
